#!/bin/bash
# Quick Test Script for Climate Research Web Dashboard

echo "========================================================================"
echo "  Climate Research System - Quick Test"
echo "========================================================================"
echo ""

# Check if Flask is installed
echo "Checking dependencies..."
python3 -c "import flask" 2>/dev/null
if [ $? -ne 0 ]; then
    echo "❌ Flask not found. Installing..."
    pip install Flask==3.0.0
else
    echo "✅ Flask is installed"
fi
echo ""

# Show instructions
echo "========================================================================"
echo "  TESTING INSTRUCTIONS"
echo "========================================================================"
echo ""
echo "1. Starting the web server..."
echo ""
echo "   Run this command in a NEW terminal:"
echo "   $ python climate_research_system/web/app.py"
echo ""
echo "2. Open your browser to:"
echo "   http://localhost:5000"
echo ""
echo "3. Test these features:"
echo ""
echo "   ✓ DASHBOARD (http://localhost:5000)"
echo "     - See 1 agent (Climate Data Agent)"
echo "     - Click 'Disable' button → agent turns gray"
echo "     - Click 'Enable' button → agent turns active"
echo "     - Click 'Reset' button → resets agent state"
echo ""
echo "   ✓ RESEARCH (http://localhost:5000/research)"
echo "     - Enter city: Paris"
echo "     - Enter country: France"
echo "     - Click 'Start Research'"
echo "     - See results appear below"
echo "     - Click 'View Full Results' or 'Download JSON'"
echo ""
echo "   ✓ RESULTS (http://localhost:5000/results)"
echo "     - See table with Berlin and Paris research"
echo "     - Click 'View' to see details in modal"
echo "     - Click 'Download' to get JSON file"
echo ""
echo "4. Test API (optional):"
echo ""
echo "   # In another terminal, test these commands:"
echo ""
echo "   # Get all agents"
echo "   $ curl http://localhost:5000/api/agents"
echo ""
echo "   # Toggle agent on/off"
echo "   $ curl -X POST http://localhost:5000/api/agents/climate_001/toggle"
echo ""
echo "   # Start research for Tokyo"
echo "   $ curl -X POST http://localhost:5000/api/research/start \\"
echo "     -H 'Content-Type: application/json' \\"
echo "     -d '{\"city\": \"Tokyo\", \"country\": \"Japan\"}'"
echo ""
echo "   # List all research"
echo "   $ curl http://localhost:5000/api/research/list"
echo ""
echo "========================================================================"
echo "  WHAT TO EXPECT"
echo "========================================================================"
echo ""
echo "✅ What works:"
echo "   - Agent management (enable/disable/reset)"
echo "   - Start research via web form"
echo "   - View and download results"
echo "   - Validation reports"
echo "   - Real-time notifications"
echo ""
echo "⚠️  Mock data (expected):"
echo "   - Climate metrics show 'null' (no real API yet)"
echo "   - Data completeness is low (~50%)"
echo "   - Warnings about missing data"
echo "   - This is NORMAL for now!"
echo ""
echo "========================================================================"
echo ""
echo "Ready to start? Run this in a NEW terminal window:"
echo ""
echo "  $ python climate_research_system/web/app.py"
echo ""
echo "Then open: http://localhost:5000"
echo ""
echo "Full testing guide: See TESTING_GUIDE.md"
echo ""
